  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "privacy policy"
  weight = 1
  identifier = "privacy policy"
  url = "/privacy-policy/"

  [[footer]]
  name = "terms & conditions"
  weight = 2
  identifier = "terms and conditions"
  url = "/terms-and-conditions/"