  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  #[[main]]
  #name = "Posts"
  #weight = 300
  #identifier = "posts"
  #url = "/post/"

  [[main]]
  name = "Contact"
  weight = 200
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "privacy policy"
  weight = 1
  identifier = "privacy policy"
  url = "/privacy-policy/"

  [[footer]]
  name = "terms & conditions"
  weight = 2
  identifier = "terms and conditions"
  url = "/terms-and-conditions/"